### ISSUE TITLE
gameanalytics_v2

### ISSUE THREAD

**Issue by dgstest3** [GameAnalytics/GA-SDK-CORONA#2]
is it available and works for corona enterprise,
because when i use
GA = require( "plugin.gameanalytics_v2" );

it say the plugin didnt found

but when i use 

GA = require( "plugin.gameanalytics" );

it say setEnabledInfoLog didnt found

**Comment by the1schwartz** [comment]
Hi,

Thanks for using GameAnalytics. For Enterprise users you need to download the plugin [here](http://download.gameanalytics.com/corona/plugin.gameanalytics_v2.zip) and follow the instructions found [here](https://github.com/GameAnalytics/GA-SDK-CORONA/wiki/Download-(Enterprise-users))
